version: '3.3'
services:
  app:
    build: ./app/
    container_name: murotani_test_env
    hostname: test_env
    environment:
        TZ: "Asia/Tokyo"
    ports:
      - "2022:2022"
    volumes:
      - ./app/src:/root/src
      - ./app/docs:/root/docs
    tty: true
    stdin_open: true